### ISSUE TITLE
When post has a photo at top dropcaps don't show up

### ISSUE THREAD

**Issue by ghost** [pimoore/microdotblog-hitchens#5]
Sorry to keep throwing stuff at you Pete. But if a post starts with an image at the top before text starts, you lose the dropcaps. I tested by moving my image to the bottom of the post and dropcaps come back,

**Comment by pimoore** [comment]
Don’t apologize, I appreciate the chance to catch bugs like these and fix them!  This is likely similar to the poetry styling issue you mentioned, so I’ll see what I can come up with.

**Comment by pimoore** [comment]
@timscrawls Only way I’ve found to get this to work is add a new .dropcap class styling into the CSS.  In order to target the first paragraph following the image, you’d just have to type : ```<p class=“dropcap”>paragraph goes here</p>```.

The advantage to this is if you wanted to lead the post with more than one image you can, while still targeting the first paragraph with the dropcap.  This will be part of the next official update to the plugin.
