### ISSUE TITLE
Alignment of microblog-conversation content

### ISSUE THREAD

**Issue by jackbaty** [pimoore/microdotblog-hitchens#8]
What a fun theme! I've noticed, at least on my blog, that the comment thread (in `.microblog_conversation`) renders at the left edge of the browser window. This is not noticeable at smaller window sizes, but looks a little off when larger. Might it be as simple as adding `margin: auto;` to `.microblog_conversation` ?

![alignment](https://user-images.githubusercontent.com/970/149621909-09168499-9af9-452d-a018-976172f13895.png)

**Comment by jackbaty** [comment]
A related, subjective, request. If the avatars were placed to the left of the replies, it would save quite a lot of vertical space. With wider windows, there's room! :). Just a thought.

**Comment by pimoore** [comment]
@jackbaty Thanks so much for trying it out, glad to read you’re enjoying it!  As far as the alignment issue I updated the plug-in recently to fix that.  If you’ve installed the theme via GitHub you’ll have to re-install it, otherwise you should see an update to the plug-in to version 1.0.1.

I really like your idea of changing the conversation layout, especially on wider screens.  Phones would make sense to keep things as is, so media query to the rescue. :)  I will play around with this and see what I can come up with! 👍🏻

**Comment by jackbaty** [comment]
Ah, I'm new to plugins. I deleted and reinstalled the plugin and it looks great now, thank you.

**Comment by pimoore** [comment]
@jackbaty Thanks for your suggestion of changing the conversation spacing on wider screens, it absolutely looks better!  This will be included in the next theme update.
